import { trpc } from "@/lib/trpc";
import { Button } from "@/components/ui/button";
import { Sparkles, RefreshCw } from "lucide-react";
import { toast } from "sonner";

interface CompatibilityInsightProps {
  matchId: number;
}

export function CompatibilityInsight({ matchId }: CompatibilityInsightProps) {
  const utils = trpc.useUtils();

  const { data: existing, isLoading: loadingExisting } = trpc.insights.get.useQuery(
    { matchId },
    { retry: false }
  );

  const generate = trpc.insights.generate.useMutation({
    onSuccess: () => utils.insights.get.invalidate({ matchId }),
    onError: (err) => toast.error(err.message ?? "Failed to generate insight"),
  });

  const insight = existing?.insight ?? (generate.data as any)?.insight;

  if (loadingExisting) {
    return (
      <div className="bg-rose-50 rounded-xl p-4 border border-rose-100 animate-pulse">
        <div className="h-4 bg-rose-100 rounded w-3/4 mb-2" />
        <div className="h-4 bg-rose-100 rounded w-1/2" />
      </div>
    );
  }

  if (insight) {
    return (
      <div className="bg-rose-50 rounded-xl p-4 border border-rose-100">
        <div className="flex items-center gap-2 mb-2">
          <Sparkles className="w-4 h-4 text-rose-500" />
          <span className="text-xs font-semibold text-rose-600 uppercase tracking-wide">Islamic Compatibility Insight</span>
        </div>
        <p className="text-sm text-gray-700 leading-relaxed italic">"{insight}"</p>
        <p className="text-xs text-gray-400 mt-2">
          Private to you. Generated by AI, inspired by Islamic guidance.
        </p>
      </div>
    );
  }

  return (
    <div className="bg-rose-50 rounded-xl p-4 border border-rose-100 text-center">
      <Sparkles className="w-6 h-6 text-rose-400 mx-auto mb-2" />
      <p className="text-sm text-gray-600 mb-3">
        Get a private Islamic compatibility insight for this match — under 150 words, framed as advice from a compassionate Islamic marriage counsellor.
      </p>
      <Button
        size="sm"
        onClick={() => generate.mutate({ matchId })}
        disabled={generate.isPending}
        className="gradient-rose text-white border-0 text-xs"
      >
        {generate.isPending ? (
          <>
            <RefreshCw className="w-3.5 h-3.5 mr-1.5 animate-spin" />
            Generating...
          </>
        ) : (
          <>
            <Sparkles className="w-3.5 h-3.5 mr-1.5" />
            Generate Insight
          </>
        )}
      </Button>
    </div>
  );
}
